version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://aliaryan786786:5H9GnBES9LDKra8q@cluster0.8xaqtba.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo
      
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: